### ISSUE TITLE
Error: watch /home/ubuntu/jbrand/dist ENOSPC

### ISSUE THREAD

**Issue by philip-symphony** [symphony-integrations/s-build#6]
See: https://circleci.com/gh/symphony-brands/jbrand/1253

```[03:44:09] Starting 'end-2-end:wdio-webdriver'...

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: watch /home/ubuntu/jbrand/dist ENOSPC
    at exports._errnoException (util.js:1026:11)
    at FSWatcher.start (fs.js:1429:19)
    at Object.fs.watch (fs.js:1456:11)
    at createFsWatchInstance (/home/ubuntu/jbrand/build-tasks/dev-brand/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/ubuntu/jbrand/build-tasks/dev-brand/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/ubuntu/jbrand/build-tasks/dev-brand/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/home/ubuntu/jbrand/build-tasks/dev-brand/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at FSWatcher.<anonymous> (/home/ubuntu/jbrand/build-tasks/dev-brand/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at FSWatcher.<anonymous> (/home/ubuntu/jbrand/build-tasks/dev-brand/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:123:15)
error Command failed with exit code 1.

yarn test returned exit code 1```

**Comment by philip-symphony** [comment]
Possibly related? https://stackoverflow.com/questions/22475849/node-js-error-enospc

**Comment by philip-symphony** [comment]
I wonder if this has to do with the plan upgrade that added another container in circle CI for the symphony-brand org?

Here's another (seemingly unrelated) failed build: https://circleci.com/gh/symphony-brands/fredericks/909
